import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/clsx";

const inter = Inter({ subsets: ["latin"], variable: "--font-paragraph" });
const oswald = Open_Sans({ subsets: ["latin"], variable: "--font-heading" });

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "font-sans antialiased",
          `${inter.variable} ${oswald.variable}`
        )}
      >
        {children}
      </body>
    </html>
  );
}
